/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006c49",
        "tertiary-container": "#71a1ff",
        "outline": "#86948a",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#00367a",
        "secondary-fixed-dim": "#ffb2b7",
        "on-tertiary-fixed-variant": "#004395",
        "tertiary-fixed-dim": "#adc6ff",
        "inverse-on-surface": "#283044",
        "on-primary-fixed": "#002113",
        "surface-container-highest": "#2d3449",
        "surface-container": "#171f33",
        "outline-variant": "#3c4a42",
        "primary": "#4edea3",
        "on-background": "#dae2fd",
        "surface-container-low": "#131b2e",
        "inverse-surface": "#dae2fd",
        "surface-dim": "#0b1326",
        "on-secondary-fixed-variant": "#92002a",
        "on-tertiary-fixed": "#001a42",
        "primary-container": "#10b981",
        "on-secondary-container": "#ffc2c4",
        "on-secondary": "#67001b",
        "tertiary-fixed": "#d8e2ff",
        "secondary-fixed": "#ffdadb",
        "on-surface-variant": "#bbcabf",
        "tertiary": "#adc6ff",
        "primary-fixed": "#6ffbbe",
        "secondary": "#ffb2b7",
        "on-surface": "#dae2fd",
        "error-container": "#93000a",
        "secondary-container": "#b50036",
        "on-primary": "#003824",
        "surface-variant": "#2d3449",
        "surface-container-lowest": "#060e20",
        "on-primary-container": "#00422b",
        "error": "#ffb4ab",
        "surface-container-high": "#222a3d",
        "on-error-container": "#ffdad6",
        "surface-tint": "#4edea3",
        "on-error": "#690005",
        "surface-bright": "#31394d",
        "on-secondary-fixed": "#40000d",
        "on-primary-fixed-variant": "#005236",
        "surface": "#0b1326",
        "on-tertiary": "#002e6a",
        "background": "#0b1326"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "header_height": "64px",
        "margin_desktop": "32px",
        "margin_mobile": "16px",
        "gutter": "24px",
        "sidebar_width": "260px",
        "stack_gap_lg": "24px",
        "stack_gap_sm": "8px",
        "stack_gap_md": "16px"
      }
    },
  },
  plugins: [],
}