/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006c49",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#004395",
        "secondary-fixed-dim": "#bec6e0",
        surface: "#f8f9ff",
        primary: "#006c49",
        "primary-container": "#10b981",
        "on-secondary": "#ffffff",
        "outline-variant": "#bbcabf",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#4edea3",
        "surface-container": "#e5eeff",
        "primary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        background: "#f8f9ff",
        "tertiary-container": "#71a1ff",
        "on-error": "#ffffff",
        outline: "#6c7a71",
        "inverse-primary": "#4edea3",
        "on-surface": "#0b1c30",
        secondary: "#565e74",
        "on-primary-fixed": "#002113",
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#5c647a",
        error: "#ba1a1a",
        "on-secondary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#adc6ff",
        tertiary: "#005ac2",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "on-background": "#0b1c30",
        "on-surface-variant": "#3c4a42",
        "on-primary-fixed-variant": "#005236",
        "secondary-container": "#dae2fd",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#00422b",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#00367a",
        "surface-container-highest": "#d3e4fe",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#001a42",
      },
      spacing: {
        "stack-md": "16px",
        "container-max": "1440px",
        "stack-lg": "32px",
        "sidebar-width": "260px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
    },
  },
  plugins: [],
};
