/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb2b7",
        "primary-fixed": "#6ffbbe",
        secondary: "#bcc7de",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        "on-surface": "#dae2fd",
        "surface-container": "#171f33",
        tertiary: "#ffb2b7",
        "surface-container-lowest": "#060e20",
        error: "#ffb4ab",
        "on-error": "#690005",
        "on-primary-fixed": "#002113",
        "on-primary-container": "#00422b",
        "inverse-primary": "#006c49",
        "surface-container-highest": "#2d3449",
        "on-tertiary-fixed": "#40000d",
        primary: "#4edea3",
        "on-secondary-container": "#aeb9d0",
        "on-background": "#dae2fd",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-on-surface": "#283044",
        "on-secondary": "#263143",
        "inverse-surface": "#dae2fd",
        "secondary-container": "#3e495d",
        "on-secondary-fixed": "#111c2d",
        "on-error-container": "#ffdad6",
        outline: "#86948a",
        "surface-bright": "#31394d",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#005236",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#ffdadb",
        "primary-container": "#10b981",
        "surface-tint": "#4edea3",
        "surface-container-low": "#131b2e",
        "on-tertiary-container": "#780021",
        "secondary-fixed": "#d8e3fb",
        surface: "#0b1326",
        "outline-variant": "#3c4a42",
        "on-surface-variant": "#bbcabf",
        "surface-variant": "#2d3449",
        "on-tertiary": "#67001b",
        background: "#0b1326",
        "error-container": "#93000a",
        "tertiary-container": "#ff7886",
        "on-tertiary-fixed-variant": "#92002a",
        "on-primary": "#003824",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sidebar_width: "260px",
        margin_desktop: "32px",
        margin_mobile: "16px",
        container_max_width: "1440px",
        gutter: "24px",
        header_height: "64px",
        base_unit: "4px",
      },
    },
  },
  plugins: [],
};
