/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#00554e",
        "surface": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "primary-container": "#1e40af",
        "on-secondary-fixed": "#0d1c2e",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-error-container": "#93000a",
        "surface-container": "#eceef0",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed-variant": "#005049",
        "on-primary-container": "#a8b8ff",
        "on-background": "#191c1e",
        "secondary-container": "#d5e3fc",
        "on-surface-variant": "#444653",
        "error-container": "#ffdad6",
        "primary-fixed": "#dde1ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#3755c3",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#001453",
        "tertiary-fixed": "#89f5e7",
        "surface-container-low": "#f2f4f6",
        "secondary": "#515f74",
        "outline": "#757684",
        "on-tertiary-fixed": "#00201d",
        "surface-dim": "#d8dadc",
        "tertiary": "#003c36",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#5fcdbf",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c4c5d5",
        "on-primary": "#ffffff",
        "inverse-primary": "#b8c4ff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#57657a",
        "error": "#ba1a1a",
        "secondary-fixed": "#d5e3fc",
        "on-secondary-fixed-variant": "#3a485b",
        "primary": "#00288e",
        "secondary-fixed-dim": "#b9c7df",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "background": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#173bab"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"]
      }
    },
  },
  plugins: [],
}
