from sqlalchemy.orm import Session
from server.models.genre import Genre
from server.models.name_component import NameComponent

GENRES_SEED_DATA = [
    {
        "code": "fantasy",
        "display_name": "Fantasy",
        "description": "Mythical, medieval, and magic-inspired character names",
        "components": [
            # Prefixes
            ("prefix", "Lord", None),
            ("prefix", "Lady", "female"),
            ("prefix", "Sir", "male"),
            ("prefix", "Archmage", None),
            ("prefix", "High Priest", None),
            ("prefix", "Elder", None),
            ("prefix", "Master", None),
            ("prefix", "Shadow", None),
            ("prefix", "Ranger", None),
            ("prefix", "Grand Master", None),
            # Descriptors
            ("descriptor", "Grim", None),
            ("descriptor", "Swift", None),
            ("descriptor", "Silent", None),
            ("descriptor", "Ancient", None),
            ("descriptor", "Radiant", None),
            ("descriptor", "Fierce", None),
            ("descriptor", "Mystic", None),
            ("descriptor", "Golden", None),
            ("descriptor", "Silver", None),
            ("descriptor", "Dark", None),
            # Bases
            ("base", "Eldrin", "male"),
            ("base", "Aeloria", "female"),
            ("base", "Thorne", "male"),
            ("base", "Lyra", "female"),
            ("base", "Gareth", "male"),
            ("base", "Morrigan", "female"),
            ("base", "Cedric", "male"),
            ("base", "Isolde", "female"),
            ("base", "Rowan", "neutral"),
            ("base", "Valen", "male"),
            ("base", "Seraphina", "female"),
            ("base", "Kaelen", "neutral"),
            ("base", "Faelar", "male"),
            ("base", "Sylvana", "female"),
            ("base", "Boran", "male"),
            ("base", "Elowen", "female"),
            ("base", "Theron", "male"),
            ("base", "Zephyr", "neutral"),
            ("base", "Darian", "male"),
            ("base", "Astrid", "female"),
            # Suffixes
            ("suffix", "Shadowweaver", None),
            ("suffix", "Stormborn", None),
            ("suffix", "Ironhand", None),
            ("suffix", "Moonwhisper", None),
            ("suffix", "Dragonbane", None),
            ("suffix", "Fireheart", None),
            ("suffix", "Nightshade", None),
            ("suffix", "Dawnbringer", None),
            ("suffix", "Starfall", None),
            ("suffix", "Windrunner", None),
            ("suffix", "Blackthorn", None),
            ("suffix", "Silvervale", None),
        ],
    },
    {
        "code": "scifi",
        "display_name": "Sci-Fi",
        "description": "Futuristic, spacefaring, and galactic character names",
        "components": [
            # Prefixes
            ("prefix", "Commander", None),
            ("prefix", "Captain", None),
            ("prefix", "Navigator", None),
            ("prefix", "Officer", None),
            ("prefix", "Admiral", None),
            ("prefix", "Doctor", None),
            ("prefix", "Cadet", None),
            ("prefix", "Specialist", None),
            # Descriptors
            ("descriptor", "Astro", None),
            ("descriptor", "Hyper", None),
            ("descriptor", "Quantum", None),
            ("descriptor", "Solar", None),
            ("descriptor", "Cosmic", None),
            ("descriptor", "Stellar", None),
            ("descriptor", "Void", None),
            ("descriptor", "Nova", None),
            # Bases
            ("base", "Orion", "male"),
            ("base", "Nova", "female"),
            ("base", "Tarkin", "male"),
            ("base", "Vesper", "female"),
            ("base", "Caelum", "male"),
            ("base", "Andromeda", "female"),
            ("base", "Rigel", "neutral"),
            ("base", "Cassian", "male"),
            ("base", "Astra", "female"),
            ("base", "Zenon", "male"),
            ("base", "Talia", "female"),
            ("base", "Joran", "male"),
            ("base", "Lyra", "female"),
            ("base", "Kaelen", "neutral"),
            ("base", "Echo", "neutral"),
            # Suffixes
            ("suffix", "Prime", None),
            ("suffix", "Vance", None),
            ("suffix", "Solari", None),
            ("suffix", "Vortex", None),
            ("suffix", "Armstrong", None),
            ("suffix", "Galileo", None),
            ("suffix", "Stargazer", None),
            ("suffix", "Pulsar", None),
            ("suffix", "Horizon", None),
            ("suffix", "Cross", None),
        ],
    },
    {
        "code": "cyberpunk",
        "display_name": "Cyberpunk",
        "description": "Neon-lit, high-tech, and dystopian rogue character names",
        "components": [
            # Prefixes
            ("prefix", "Netrunner", None),
            ("prefix", "Agent", None),
            ("prefix", "Ghost", None),
            ("prefix", "Cipher", None),
            ("prefix", "Neon", None),
            ("prefix", "Glitch", None),
            ("prefix", "Zero", None),
            ("prefix", "Vector", None),
            # Descriptors
            ("descriptor", "Chrome", None),
            ("descriptor", "Shadow", None),
            ("descriptor", "Static", None),
            ("descriptor", "Wired", None),
            ("descriptor", "Rogue", None),
            ("descriptor", "Toxic", None),
            ("descriptor", "Digital", None),
            ("descriptor", "Turbo", None),
            # Bases
            ("base", "Jax", "male"),
            ("base", "Nyx", "female"),
            ("base", "Renn", "male"),
            ("base", "Vesper", "female"),
            ("base", "Kaelen", "neutral"),
            ("base", "Dex", "male"),
            ("base", "Echo", "neutral"),
            ("base", "Raven", "female"),
            ("base", "Silas", "male"),
            ("base", "Matrix", "neutral"),
            ("base", "Kira", "female"),
            ("base", "Ryder", "male"),
            ("base", "Zane", "male"),
            ("base", "Nova", "female"),
            # Suffixes
            ("suffix", "Kovacs", None),
            ("suffix", "Byte", None),
            ("suffix", "Mercer", None),
            ("suffix", "Vance", None),
            ("suffix", "Cross", None),
            ("suffix", "Synapse", None),
            ("suffix", "Steel", None),
            ("suffix", "Black", None),
            ("suffix", "Wire", None),
            ("suffix", "Shift", None),
        ],
    },
    {
        "code": "mystery",
        "display_name": "Mystery",
        "description": "Enigmatic, detective, and noir-inspired character names",
        "components": [
            # Prefixes
            ("prefix", "Detective", None),
            ("prefix", "Inspector", None),
            ("prefix", "Agent", None),
            ("prefix", "Professor", None),
            ("prefix", "Doctor", None),
            ("prefix", "Madam", "female"),
            ("prefix", "Sir", "male"),
            ("prefix", "Counselor", None),
            # Descriptors
            ("descriptor", "Silent", None),
            ("descriptor", "Grim", None),
            ("descriptor", "Shadowy", None),
            ("descriptor", "Clever", None),
            ("descriptor", "Shrewd", None),
            ("descriptor", "Subtle", None),
            ("descriptor", "Mysterious", None),
            ("descriptor", "Sharp", None),
            # Bases
            ("base", "Arthur", "male"),
            ("base", "Vivian", "female"),
            ("base", "Julian", "male"),
            ("base", "Eleanor", "female"),
            ("base", "Victor", "male"),
            ("base", "Clara", "female"),
            ("base", "Raymond", "male"),
            ("base", "Evelyn", "female"),
            ("base", "Gideon", "male"),
            ("base", "Beatrice", "female"),
            ("base", "Vincent", "male"),
            ("base", "Agatha", "female"),
            ("base", "Felix", "male"),
            ("base", "Morgan", "neutral"),
            # Suffixes
            ("suffix", "Blackwood", None),
            ("suffix", "Holmes", None),
            ("suffix", "Cross", None),
            ("suffix", "Sterling", None),
            ("suffix", "Marlowe", None),
            ("suffix", "Holloway", None),
            ("suffix", "Pendleton", None),
            ("suffix", "Vance", None),
            ("suffix", "Dupont", None),
            ("suffix", "Sinclair", None),
        ],
    },
    {
        "code": "historical",
        "display_name": "Historical",
        "description": "Classic, period-accurate, and vintage character names",
        "components": [
            # Prefixes
            ("prefix", "Lord", "male"),
            ("prefix", "Lady", "female"),
            ("prefix", "Baron", "male"),
            ("prefix", "Baroness", "female"),
            ("prefix", "Duke", "male"),
            ("prefix", "Duchess", "female"),
            ("prefix", "Sir", "male"),
            ("prefix", "Dame", "female"),
            ("prefix", "Captain", None),
            ("prefix", "General", None),
            # Descriptors
            ("descriptor", "Valiant", None),
            ("descriptor", "Noble", None),
            ("descriptor", "Grand", None),
            ("descriptor", "Gallant", None),
            ("descriptor", "Austere", None),
            ("descriptor", "Brave", None),
            ("descriptor", "Stalwart", None),
            ("descriptor", "Wise", None),
            # Bases
            ("base", "William", "male"),
            ("base", "Victoria", "female"),
            ("base", "Edward", "male"),
            ("base", "Elizabeth", "female"),
            ("base", "George", "male"),
            ("base", "Charlotte", "female"),
            ("base", "Henry", "male"),
            ("base", "Margaret", "female"),
            ("base", "Alexander", "male"),
            ("base", "Catherine", "female"),
            ("base", "Richard", "male"),
            ("base", "Anne", "female"),
            ("base", "Charles", "male"),
            ("base", "Eleanor", "female"),
            # Suffixes
            ("suffix", "Wellington", None),
            ("suffix", "Lancaster", None),
            ("suffix", "Windsor", None),
            ("suffix", "Montague", None),
            ("suffix", "Somerset", None),
            ("suffix", "Pembroke", None),
            ("suffix", "Hastings", None),
            ("suffix", "Beaufort", None),
            ("suffix", "Fitzgerald", None),
            ("suffix", "Churchill", None),
        ],
    },
    {
        "code": "general",
        "display_name": "General",
        "description": "Versatile, universal, and contemporary character names",
        "components": [
            # Prefixes
            ("prefix", "Captain", None),
            ("prefix", "Doctor", None),
            ("prefix", "Coach", None),
            ("prefix", "Chief", None),
            ("prefix", "Officer", None),
            ("prefix", "Professor", None),
            # Descriptors
            ("descriptor", "Swift", None),
            ("descriptor", "Bright", None),
            ("descriptor", "Brave", None),
            ("descriptor", "Clever", None),
            ("descriptor", "True", None),
            ("descriptor", "Bold", None),
            # Bases
            ("base", "Alex", "neutral"),
            ("base", "Jordan", "neutral"),
            ("base", "Taylor", "neutral"),
            ("base", "Morgan", "neutral"),
            ("base", "Casey", "neutral"),
            ("base", "Sam", "neutral"),
            ("base", "Riley", "neutral"),
            ("base", "Logan", "neutral"),
            ("base", "Avery", "neutral"),
            ("base", "Quinn", "neutral"),
            ("base", "Oliver", "male"),
            ("base", "Emma", "female"),
            ("base", "Liam", "male"),
            ("base", "Olivia", "female"),
            ("base", "Noah", "male"),
            ("base", "Ava", "female"),
            ("base", "Ethan", "male"),
            ("base", "Sophia", "female"),
            ("base", "Lucas", "male"),
            ("base", "Mia", "female"),
            # Suffixes
            ("suffix", "Smith", None),
            ("suffix", "Johnson", None),
            ("suffix", "Miller", None),
            ("suffix", "Davis", None),
            ("suffix", "Wilson", None),
            ("suffix", "Taylor", None),
            ("suffix", "Anderson", None),
            ("suffix", "Thomas", None),
            ("suffix", "Jackson", None),
            ("suffix", "White", None),
            ("suffix", "Harris", None),
            ("suffix", "Martin", None),
        ],
    },
]


def seed_data(db: Session) -> None:
    """Seed genres and component pools idempotently."""
    for gdata in GENRES_SEED_DATA:
        genre = db.query(Genre).filter(Genre.code == gdata["code"]).first()
        if not genre:
            genre = Genre(
                code=gdata["code"],
                display_name=gdata["display_name"],
                description=gdata["description"],
            )
            db.add(genre)
            db.flush()

        # Seed components if not present
        existing_components = {
            (c.component_type, c.value, c.sub_tag)
            for c in db.query(NameComponent).filter(NameComponent.genre_id == genre.id).all()
        }

        for comp_type, value, sub_tag in gdata["components"]:
            if (comp_type, value, sub_tag) not in existing_components:
                comp = NameComponent(
                    genre_id=genre.id,
                    component_type=comp_type,
                    value=value,
                    sub_tag=sub_tag,
                )
                db.add(comp)
    db.commit()
