
"""Initial migration

Revision ID: 1234567890
Revises: 
Create Date: 2024-05-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1234567890'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_transactions',
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tokenized_card_number', sa.String(), nullable=False),
    sa.Column('daily_spend_threshold', sa.Numeric(), nullable=False),
    sa.Column('alert_delivery_channel', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('spend_alerts',
    sa.Column('alert_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tokenized_card_number', sa.String(), nullable=False),
    sa.Column('daily_spend_threshold', sa.Numeric(), nullable=False),
    sa.Column('alert_delivery_channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('tokenized_card_number')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend_alerts')
    op.drop_table('otp_transactions')
    # ### end Alembic commands ###
